/**
 * Import the brain's "Customer 360" legacy profiles into Postgres.
 *
 * Source (generated by `brain/brain/dossier.py --export`):
 *   brain/data/master/legacy-profiles.jsonl   one slim JSON dossier per household
 *
 * Writes two read-only tables consumed by the admin "Legacy history" panel:
 *   legacy_profiles         one row per legacy household (summary + data JSON)
 *   legacy_profile_emails   email -> profile lookup (resolves a current Person)
 *
 * SAFETY
 *   - DRY-RUN by default. Pass `--confirm` to actually write.
 *   - Idempotent: profiles upserted by householdKey; emails upserted by address.
 *   - Email conflicts (a shared address across two legacy households) resolve to
 *     the profile whose householdKey == that email (its "own" household).
 *   - NEVER touches the live CRM tables — this is reference data only.
 *
 * Run: npx tsx scripts/import-legacy-profiles.ts [--confirm] [--file <path>]
 */
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { PrismaClient, type Prisma } from "@prisma/client";

const prisma = new PrismaClient();

interface LegacyProfileRecord {
  householdKey: string;
  displayName: string;
  memberNames: string[];
  ownerEmails: string[];
  totalPaidCents: number;
  totalRefundedCents: number;
  bookingCount: number;
  emailCount: number;
  complaintCount: number;
  firstSeen: string | null;
  lastSeen: string | null;
  data: unknown;
}

function dateOf(raw: string | null): Date | null {
  if (!raw || !/^\d{4}-\d{2}-\d{2}$/.test(raw)) return null;
  const d = new Date(raw + "T00:00:00Z");
  return Number.isNaN(d.getTime()) ? null : d;
}

function parseJsonl(text: string): LegacyProfileRecord[] {
  const out: LegacyProfileRecord[] = [];
  for (const line of text.split("\n")) {
    const t = line.trim();
    if (!t) continue;
    out.push(JSON.parse(t) as LegacyProfileRecord);
  }
  return out;
}

async function main() {
  const confirm = process.argv.includes("--confirm");
  const fileIdx = process.argv.indexOf("--file");
  const here = path.dirname(fileURLToPath(import.meta.url));
  const file =
    fileIdx >= 0 && process.argv[fileIdx + 1]
      ? path.resolve(process.argv[fileIdx + 1])
      : path.resolve(here, "../../brain/data/master/legacy-profiles.jsonl");

  const profiles = parseJsonl(readFileSync(file, "utf8"));

  console.log(
    `${confirm ? "WRITING" : "DRY-RUN"} legacy import from ${file}\n` +
      `  profiles=${profiles.length}`,
  );

  // Resolve email -> householdKey, preferring the profile that owns the email.
  const emailToKey = new Map<string, string>();
  for (const p of profiles) {
    for (const raw of p.ownerEmails ?? []) {
      const email = raw.trim().toLowerCase();
      if (!email) continue;
      const existing = emailToKey.get(email);
      if (!existing || email === p.householdKey.toLowerCase()) {
        emailToKey.set(email, p.householdKey);
      }
    }
  }

  let profilesWritten = 0;
  let emailsWritten = 0;
  const keyToId = new Map<string, string>();

  for (const p of profiles) {
    if (confirm) {
      const row = await prisma.legacyProfile.upsert({
        where: { householdKey: p.householdKey },
        create: {
          householdKey: p.householdKey,
          displayName: p.displayName,
          memberNames: p.memberNames ?? [],
          totalPaidCents: p.totalPaidCents ?? 0,
          totalRefundedCents: p.totalRefundedCents ?? 0,
          bookingCount: p.bookingCount ?? 0,
          emailCount: p.emailCount ?? 0,
          complaintCount: p.complaintCount ?? 0,
          firstSeen: dateOf(p.firstSeen),
          lastSeen: dateOf(p.lastSeen),
          data: p.data as Prisma.InputJsonValue,
        },
        update: {
          displayName: p.displayName,
          memberNames: p.memberNames ?? [],
          totalPaidCents: p.totalPaidCents ?? 0,
          totalRefundedCents: p.totalRefundedCents ?? 0,
          bookingCount: p.bookingCount ?? 0,
          emailCount: p.emailCount ?? 0,
          complaintCount: p.complaintCount ?? 0,
          firstSeen: dateOf(p.firstSeen),
          lastSeen: dateOf(p.lastSeen),
          data: p.data as Prisma.InputJsonValue,
          importedAt: new Date(),
        },
        select: { id: true },
      });
      keyToId.set(p.householdKey, row.id);
    }
    profilesWritten++;
  }

  for (const [email, householdKey] of emailToKey) {
    const profileId = keyToId.get(householdKey);
    if (confirm && profileId) {
      await prisma.legacyProfileEmail.upsert({
        where: { email },
        create: { email, profileId },
        update: { profileId },
      });
    }
    emailsWritten++;
  }

  console.log(
    `\nDone (${confirm ? "written" : "dry-run, nothing written"}):\n` +
      `  profiles: ${profilesWritten}\n` +
      `  emails:   ${emailsWritten}`,
  );
  if (!confirm) {
    console.log("\nRe-run with --confirm to write.");
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
