/**
 * Parallel-mode import from the Higgins "brain" master dataset.
 *
 * Populates households, account owners, and ACTIVE students so the membership
 * gate + CRM are seeded for the summer — WITHOUT importing full history.
 * GoTimmy stays the system of record for history during the parallel period.
 *
 * Source CSVs (generated by `brain/brain/export_portal.py`):
 *   <dir>/people.csv      personId,firstName,lastName,email,phones,roles,inCalendar
 *   <dir>/students.csv    studentId,firstName,lastName,dateOfBirth,gender,skillLevel,
 *                         enrollmentStatus,householdEmails,enrollmentCount,ambiguousNoDob
 *   <dir>/households.csv  ownerEmail,displayName,memberCount,studentIds
 *
 * SAFETY
 *   - DRY-RUN by default. Pass `--confirm` to actually write.
 *   - Run on STAGING first (see handoff/cutover-runbook.md).
 *   - Idempotent: owners matched by email; students matched by
 *     (household, name, dob) so re-runs don't duplicate.
 *   - Imported people get generated UUIDs and NO auth user; they bridge to a
 *     Supabase login by email on first sign-in.
 *
 * Run: npx tsx scripts/import-from-brain.ts [--confirm] [--dir <path>]
 */
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { randomUUID } from "node:crypto";

import { PrismaClient, type Gender, type StudentEnrollmentStatus } from "@prisma/client";

const prisma = new PrismaClient();

// ── tiny quote-aware CSV parser ────────────────────────────────────────────
function parseCsv(text: string): Record<string, string>[] {
  const rows: string[][] = [];
  let field = "";
  let row: string[] = [];
  let inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') {
          field += '"';
          i++;
        } else inQuotes = false;
      } else field += c;
    } else if (c === '"') {
      inQuotes = true;
    } else if (c === ",") {
      row.push(field);
      field = "";
    } else if (c === "\n" || c === "\r") {
      if (c === "\r" && text[i + 1] === "\n") i++;
      row.push(field);
      field = "";
      if (row.some((v) => v !== "")) rows.push(row);
      row = [];
    } else field += c;
  }
  if (field !== "" || row.length > 0) {
    row.push(field);
    if (row.some((v) => v !== "")) rows.push(row);
  }
  if (rows.length === 0) return [];
  const header = rows[0];
  return rows.slice(1).map((r) => {
    const o: Record<string, string> = {};
    header.forEach((h, idx) => (o[h] = (r[idx] ?? "").trim()));
    return o;
  });
}

function genderOf(raw: string): Gender | null {
  switch (raw.toUpperCase()) {
    case "MALE":
      return "male";
    case "FEMALE":
      return "female";
    case "OTHER":
      return "other";
    default:
      return null;
  }
}

function enrollmentStatusOf(raw: string): StudentEnrollmentStatus {
  return raw.toUpperCase() === "ACTIVE" ? "active" : "paused";
}

function dobOf(raw: string): Date | null {
  if (!raw || !/^\d{4}-\d{2}-\d{2}$/.test(raw)) return null;
  const d = new Date(raw + "T00:00:00Z");
  return Number.isNaN(d.getTime()) ? null : d;
}

function ageFrom(dob: Date | null): number | null {
  if (!dob) return null;
  const now = new Date();
  let age = now.getUTCFullYear() - dob.getUTCFullYear();
  const m = now.getUTCMonth() - dob.getUTCMonth();
  if (m < 0 || (m === 0 && now.getUTCDate() < dob.getUTCDate())) age--;
  return age;
}

interface Stats {
  ownersCreated: number;
  ownersReused: number;
  householdsCreated: number;
  studentsCreated: number;
  studentsSkipped: number;
}

async function main() {
  const confirm = process.argv.includes("--confirm");
  const dirIdx = process.argv.indexOf("--dir");
  const here = path.dirname(fileURLToPath(import.meta.url));
  const dir =
    dirIdx >= 0 && process.argv[dirIdx + 1]
      ? path.resolve(process.argv[dirIdx + 1])
      : path.resolve(here, "../../brain/data/master/portal");

  const people = parseCsv(readFileSync(path.join(dir, "people.csv"), "utf8"));
  const students = parseCsv(readFileSync(path.join(dir, "students.csv"), "utf8"));
  const households = parseCsv(
    readFileSync(path.join(dir, "households.csv"), "utf8"),
  );

  const peopleByEmail = new Map<string, Record<string, string>>();
  for (const p of people) {
    if (p.email) peopleByEmail.set(p.email.toLowerCase(), p);
  }

  // Active students grouped by household owner email.
  const activeByOwner = new Map<string, Record<string, string>[]>();
  for (const s of students) {
    if (s.enrollmentStatus?.toUpperCase() !== "ACTIVE") continue;
    for (const em of (s.householdEmails || "").split(";")) {
      const key = em.trim().toLowerCase();
      if (!key) continue;
      if (!activeByOwner.has(key)) activeByOwner.set(key, []);
      activeByOwner.get(key)!.push(s);
    }
  }

  const stats: Stats = {
    ownersCreated: 0,
    ownersReused: 0,
    householdsCreated: 0,
    studentsCreated: 0,
    studentsSkipped: 0,
  };

  console.log(
    `${confirm ? "WRITING" : "DRY-RUN"} import from ${dir}\n` +
      `  households=${households.length} people=${people.length} ` +
      `activeStudents=${[...activeByOwner.values()].reduce((a, v) => a + v.length, 0)}`,
  );

  for (const h of households) {
    const ownerEmail = h.ownerEmail?.toLowerCase();
    if (!ownerEmail) continue;
    const ownerInfo = peopleByEmail.get(ownerEmail);
    const ownerFirst = ownerInfo?.firstName || h.displayName || "Member";
    const ownerLast = ownerInfo?.lastName || "";

    // Owner: reuse by existing email, else create Person + EmailAddress.
    const existingEmail = await prisma.emailAddress.findFirst({
      where: { address: ownerEmail },
      select: { personId: true },
    });
    let ownerId = existingEmail?.personId ?? null;
    if (ownerId) {
      stats.ownersReused++;
    } else {
      stats.ownersCreated++;
      ownerId = randomUUID();
      if (confirm) {
        await prisma.person.create({
          data: {
            id: ownerId,
            firstName: ownerFirst,
            lastName: ownerLast,
            country: "NL",
            emails: {
              create: {
                address: ownerEmail,
                kind: "personal",
                isPrimary: true,
              },
            },
          },
        });
      }
    }

    // Household: reuse by primary contact, else create.
    let householdId: string | null = null;
    if (ownerId) {
      const existingHh = await prisma.household.findFirst({
        where: { primaryContactPersonId: ownerId },
        select: { id: true },
      });
      householdId = existingHh?.id ?? null;
    }
    if (!householdId) {
      stats.householdsCreated++;
      if (confirm && ownerId) {
        const hh = await prisma.household.create({
          data: {
            displayName: h.displayName || `${ownerFirst} ${ownerLast}`.trim(),
            primaryContactPersonId: ownerId,
            country: "NL",
            members: {
              create: { personId: ownerId, roleInHousehold: "adult" },
            },
          },
          select: { id: true },
        });
        householdId = hh.id;
      }
    }

    // Active students in this household.
    for (const s of activeByOwner.get(ownerEmail) ?? []) {
      const dob = dobOf(s.dateOfBirth);
      // De-dupe: skip if a member with same name + dob already exists here.
      if (confirm && householdId) {
        const dupe = await prisma.householdMember.findFirst({
          where: {
            householdId,
            person: {
              firstName: s.firstName,
              lastName: s.lastName,
              dateOfBirth: dob,
            },
          },
          select: { personId: true },
        });
        if (dupe) {
          stats.studentsSkipped++;
          continue;
        }
      }
      stats.studentsCreated++;
      if (confirm && householdId) {
        const age = ageFrom(dob);
        const studentId = randomUUID();
        await prisma.person.create({
          data: {
            id: studentId,
            firstName: s.firstName || "Student",
            lastName: s.lastName || "",
            country: "NL",
            dateOfBirth: dob,
            gender: genderOf(s.gender) ?? undefined,
            student: {
              create: {
                enrollmentStatus: enrollmentStatusOf(s.enrollmentStatus),
                joinedOn: new Date(),
              },
            },
            householdMember: {
              create: {
                householdId,
                roleInHousehold: age != null && age >= 18 ? "adult" : "child",
              },
            },
          },
        });
      }
    }
  }

  console.log(
    `\nDone (${confirm ? "written" : "dry-run, nothing written"}):\n` +
      `  owners: +${stats.ownersCreated} created, ${stats.ownersReused} reused\n` +
      `  households: +${stats.householdsCreated}\n` +
      `  students: +${stats.studentsCreated} created, ${stats.studentsSkipped} skipped (dupes)`,
  );
  if (!confirm) {
    console.log("\nRe-run with --confirm to write. Use a STAGING DB first.");
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
